---
- name: Install PostgreSql
  become: true
  become_method: sudo
  apt:
    name: "{{ packages }}"
    update_cache: yes 
    state: latest

  vars:
    packages:
      - postgresql
      - libpq-dev
      - python-psycopg2

- name: Add dev database user
  become: true
  become_user: postgres
  postgresql_user:
    name: vagrant
    password: "{{ vagrant_postgresql_password }}"
    role_attr_flags: CREATEDB,NOSUPERUSER
    state: present


