---
- name: Get frequently-used bash scripts from github
  git:
    repo: ssh://git@github.com/ryanhhtan/my-bash-scripts.git
    dest: "/{{ ansible_user_dir }}/code/my-bash-scripts"

- name: Ensure frequently-used bash scripts path is added to path
  lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    line: "export PATH=$PATH:{{ ansible_user_dir }}/code/my-bash-scripts"
    state: present

- name: Get vim settings from github 
  git:
    repo: ssh://git@github.com/ryanhhtan/vimsettings.git
    dest: "/{{ ansible_user_dir }}/code/vimsettings"

- name: Apply vim settings (with symlink)
  file:
    src: "{{ ansible_user_dir }}/code/vimsettings/{{ item.filename}}"
    dest: "{{ ansible_user_dir }}/{{ item.filename }}"
    state: link
  with_items: 
    - { filename: '.vimrc' }
    - { filename: '.tmux.conf' }
