- name: Copy the SSH key pairs  
  copy: 
    src: keys/{{ item }}
    dest: ~/.ssh/{{ item }}
    mode: 0600
  with_items:
    # The files are encrypted by vault
    - id_rsa
    - id_rsa.pub

- name: Copy GPG key pairs  
  copy: 
    src: keys/gpg/{{ item }}
    dest: ~/.gnupg/{{ item }}
    mode: 0600
  with_items:
    # The files are encrypted by vault
    - pubring.gpg
    - secring.gpg

- name: Ensure github.com is a known host
  lineinfile:
    dest: ~/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"

- name: Create a folder to store local repositores.
  become: true
  become_method: sudo
  file:
    path: /repos
    state: directory
    mode: 0755
    owner: vagrant
    group: vagrant

- name: Add git global config 
  git_config:
    scope: global
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - { name: user.name, value: Hai Hua (Ryan) Tan }
    - { name: user.email, value: ryanhhtan@gmail.com }
    - { name: push.default, value: simple }
    - { name: user.signingkey, value: "{{ git_signingkey }}" }

