- name: Copy the SSH key pairs  
  copy: 
    src: keys/{{ item }}
    dest: ~/.ssh/{{ item }}
    mode: 0600
  with_items:
    # The files are encrypted by vault
    - id_rsa
    - id_rsa.pub

- name: Ensure github.com is a known host
  lineinfile:
    dest: ~/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"

- name: Create a folder to store local repositores.
  become: true
  become_method: sudo
  file:
    path: /repos
    state: directory
    mode: 0755
    owner: vagrant
    group: vagrant
