---
- name: Install essential dev-util packages
  become: yes
  become_method: sudo
  apt: 
    name: "{{packages}}"
    # update_cache: yes
    # state: latest
  vars:
    packages: 
      - cmake
      - zip
      - unzip
