- name: Download Nodejs 12.x setup tool
  get_url:
    url: https://deb.nodesource.com/setup_12.x 
    dest: /tmp/nodejs_setuptool
    mode: 0755

- name: Setup Nodejs 12.x ppa
  become: true
  become_method: sudo
  command: "bash /tmp/nodejs_setuptool"

- name: Install Nodejs 12.x
  become: true
  become_method: sudo
  apt:
    pkg: nodejs
    update_cache: true
    state: latest

