--- 
- name: Check if composer installed 
  shell: test -f /bin/composer && echo yes || echo no
  register: composer_installed

- name: Install composer with the install script 
  when: composer_installed.stdout == "no"
  become: true
  become_method: sudo
  command: "install-php-composer"
