- name: Get composer install script from Github
  git:
    repo: ssh://git@github.com/ryanhhtan/composer-install.git
    dest: "/{{ ansible_user_dir }}/code/composer-install"

- name: Install composer with the install script 
  become: true
  become_method: sudo
  command: "bash {{ ansible_user_dir }}/code/composer-install/install.sh"
