- name: Insert SSH key for accessing the host 
  blockinfile:
    block: "{{ lookup('file', 'keys/id_rsa.pub') }}" # The file is encrypted
    dest: "{{ ansible_user_dir }}/.ssh/authorized_keys"
    backup: no
  notify: 
    - restart sshd

- name : Set timezone to America/Vancouver
  become: yes
  become_method: sudo
  timezone: 
    name: America/Vancouver

- name: Ensure apt-get is up to date
  become: yes
  become_method: sudo
  apt: 
    update_cache: yes

- name: Install basic packages
  become: yes
  become_method: sudo
  apt: 
    name: "{{packages}}"
    # update_cache: yes
    # state: latest
  vars:
    packages: 
      - python3-pip
      - tmux
      - zip
      - unzip
      - ctags
      - silversearcher-ag
      - httpie



# - name: Disable IPv6
#   become: true
#   become_method: sudo
#   lineinfile:
#     path: /etc/sysctl.conf
#     line: "{{ item }}"
#     state: present
#   with_items:
#     - net.ipv6.conf.all.disable_ipv6 = 1
#     - net.ipv6.conf.default.disable_ipv6 = 1
#     - net.ipv6.conf.lo.disable_ipv6 = 1
#   notify: apply sysctl

- name: Install docker 
  become: true
  become_method: sudo
  apt: 
    pkg: docker.io
    update_cache: yes 
    state: latest
  notify: add docker user group

- name: Get frequently-used bash scripts from github
  git:
    repo: ssh://git@github.com/ryanhhtan/my-bash-scripts.git
    dest: "/{{ ansible_user_dir }}/code/my-bash-scripts"

- name: Ensure frequently-used bash scripts path is added to path
  lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    line: "export PATH=$PATH:{{ ansible_user_dir }}/code/my-bash-scripts"
    state: present
  notify: source bashrc
