- name: Insert SSH key for accessing the host 
  blockinfile:
    block: "{{ lookup('file', 'keys/id_rsa.pub') }}"
    dest: "{{ ansible_user_dir }}/.ssh/authorized_keys"
    backup: no
  notify: 
    - restart sshd

- name : Set timezone to America/Vancouver
  become: yes
  become_method: sudo
  timezone: 
    name: America/Vancouver

- name: Ensure apt-get is up to date
  become: yes
  become_method: sudo
  apt: 
    update_cache: yes

- name: Set vim 8.1 ppa
  become: yes
  become_method: sudo
  apt_repository:
    repo: ppa:jonathonf/vim
    state: present

- name: Install preference packages
  become: yes
  become_method: sudo
  apt: 
    name: "{{packages}}"
    update_cache: yes
    state: latest
  vars:
    packages: 
      - python3-pip
      - tmux
      - ctags
      - silversearcher-ag
      - httpie
      - docker.io
      - vim 

- name: Add docker user group
  become: true
  become_method: sudo
  command: usermod -a -G docker {{ansible_user}} 

