- name: install java8
  become: yes
  become_method: sudo
  apt: pkg=default-jdk state=latest update_cache=yes

- name: Create a folder to store frequently-used jars
  file:
    path: /home/vagrant/jars
    state: directory
    mode: 0755
    owner: vagrant
    group: vagrant

- name: Download Lombok
  get_url:
    url: https://projectlombok.org/downloads/lombok.jar
    dest: /home/vagrant/jars/lombok.jar

