- name: Insert SSH key for accessing the host 
  blockinfile:
    block: "{{ lookup('file', 'keys/id_rsa.pub') }}" # The file is encrypted
    dest: "~/.ssh/authorized_keys"
    backup: no
  notify: 
    - restart sshd

- name: Ensure apt-get is up to date
  become: yes
  become_method: sudo
  apt: update_cache=yes

- name: Install pip 
  become: yes
  become_method: sudo
  apt: pkg="python3-pip" update_cache=yes state=latest



