- name: Set vim 8.0 ppa
  become: yes
  become_method: sudo
  apt_repository:
    repo: ppa:jonathonf/vim
    state: present

- name: Install vim 8.0
  become: yes
  become_method: sudo
  apt: name=vim update_cache=yes state=latest

- name: install neovim
  pip:
    executable: pip3
    name: neovim

- name: Get vim settings from github 
  git:
    repo: ssh://git@github.com/ryanhhtan/vimsettings.git
    dest: "/{{ ansible_user_dir }}/code/vimsettings"

- name: Apply vim settings (with symlink)
  file:
    src: "{{ ansible_user_dir }}/code/vimsettings/{{ item.filename}}"
    dest: "{{ ansible_user_dir }}/{{ item.filename }}"
    state: link
  with_items: 
    - { filename: '.vimrc' }
    - { filename: '.tmux.conf' }
