- name: Get vim settings from github 
  git:
    repo: ssh://git@github.com/ryanhhtan/vimsettings.git
    dest: /repos/vimsettings

- name: Copy my vimrc from my repo 
  copy:
    src: /repos/vimsettings/ubuntu/.vimrc
    dest: ~/.vimrc
